ALTER TABLE public.lays
  ADD COLUMN IF NOT EXISTS cut_no TEXT,
  ADD COLUMN IF NOT EXISTS marker_length NUMERIC,
  ADD COLUMN IF NOT EXISTS ratio TEXT,
  ADD COLUMN IF NOT EXISTS total_yards NUMERIC;